# Generated by Django 3.2.15 on 2023-09-30 15:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230923_1828'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Необработанный'), ('Assembling', 'Cборка'), ('Delivery', 'Доставка'), ('Completed', 'Выполнен')], default='Unprocessed', max_length=200, verbose_name='Статус'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productset',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
