# Generated by Django 3.2.15 on 2023-09-30 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_auto_20230930_1840'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('Unprocessed', 'Необработанный'), ('Assembling', 'Cборка'), ('Delivery', 'Доставка'), ('Completed', 'Выполнен')], db_index=True, max_length=200, verbose_name='Статус'),
        ),
    ]
