# Generated by Django 3.2.15 on 2023-09-30 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0046_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.CharField(default='', max_length=200, verbose_name='Комментарий'),
            preserve_default=False,
        ),
    ]
