# Generated by Django 3.2.15 on 2023-10-14 13:38

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0047_order_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='called_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата звонка'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата создания'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivered_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Дата доставки'),
            preserve_default=False,
        ),
    ]
